"""Migracion Inicial

Revision ID: 922ca806cf16
Revises: 
Create Date: 2024-09-18 10:50:26.538169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922ca806cf16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('mqtt_key', sa.String(length=300), nullable=False),
    sa.Column('nombres', sa.String(length=200), nullable=False),
    sa.Column('apellidos', sa.String(length=200), nullable=False),
    sa.Column('verified_check', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=400), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', 'manager', name='userroleenum'), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='userstatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cuerpos_aguas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('altitud', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('nodos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aplicacion_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('cuerpo_agua_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuerpo_agua_id'], ['cuerpos_aguas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('variable', sa.String(length=30), nullable=True),
    sa.Column('control', sa.Float(), nullable=False),
    sa.Column('operacion', sa.Enum('MY', 'MYIG', 'ME', 'MEIG', 'IG', name='alertoperacionenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nodo_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datos_nodos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_dato', sa.DateTime(), nullable=True),
    sa.Column('gateway_id', sa.UUID(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('turbidez', sa.Float(), nullable=True),
    sa.Column('oxigeno_disuelto', sa.Float(), nullable=True),
    sa.Column('conductividad', sa.Float(), nullable=True),
    sa.Column('solido_disuelto', sa.Float(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('nodo_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas_detalles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variable', sa.String(length=30), nullable=True),
    sa.Column('control', sa.Float(), nullable=False),
    sa.Column('operacion', sa.Enum('MY', 'MYIG', 'ME', 'MEIG', 'IG', name='alertoperacionenum'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('alerta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas_detalles')
    op.drop_table('datos_nodos')
    op.drop_table('alertas')
    op.drop_table('nodos')
    op.drop_table('cuerpos_aguas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
